### Listar usuários de uma empresa
GET http://localhost:8090/api/user/users

### Criar um novo usuário
POST http://localhost:8090/api/users
Content-Type: application/json

{
  "name": "Novo Usuário",
  "email": "novo@email.com"
}

### Listar todos os usuários
GET http://localhost:8090/api/users
Authorization: Bearer <token>

### Buscar um usuário pelo ID
GET http://localhost:8090/api/users/1
Authorization: Bearer <token>

### Atualizar um usuário
PUT http://localhost:8090/api/users/123
Content-Type: application/json
Authorization: Bearer <token>

{
  "name": "Usuário Atualizado"
}

### Pesquisar tarefa
GET http://localhost:8090/api/tasks/64962910996d31f3f924e916
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjFjYzUzMWI3MTdmOTgxOTNmM2QwZSIsImNvbXBhbnkiOiI2NDg3YzliNzNhNGU0NDg2YmFhMzM5ZGYiLCJlbWFpbCI6InRoaWFnb0Bnb29nbGUuY29tIiwibmFtZSI6IlRoaWFnbyIsImlhdCI6MTczNDQ3Nzk1M30.pEBOa8xV9pcN8v5NiXJgwpn0Sf67sNa4fAqELWYyLo0
